// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/_sitemap-urls': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/_sitemap-urls').default>>>>
    }
    '/api/feedback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feedback.post').default>>>>
    }
    '/api/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search.get').default>>>>
    }
    '/api/portal/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../layers/portal/server/api/portal/search.get').default>>>>
    }
    '/api/stripe/create-checkout-session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../layers/portal/server/api/stripe/create-checkout-session.post').default>>>>
    }
    '/api/stripe/create-portal-link': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../layers/portal/server/api/stripe/create-portal-link.post').default>>>>
    }
    '/api/stripe/webhooks': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../layers/portal/server/api/stripe/webhooks.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.0.0_eslint@8.56.0_ioredis@5.4.1_magicast@0.3_2vjq6nn6zr6vkankfqsox74fj4/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.3.1_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3__vue@3.4.34_typescript@5.5.4_/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__site-config__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/nitro/routes/__site-config__/debug').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+robots@4.0.2_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3_5ypj5ppfq3c6kjdx7sb4j642ty/node_modules/@nuxtjs/robots/dist/runtime/nitro/server/robots-txt').default>>>>
    }
    '/__robots__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+robots@4.0.2_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3_5ypj5ppfq3c6kjdx7sb4j642ty/node_modules/@nuxtjs/robots/dist/runtime/nitro/server/__robots__/debug').default>>>>
    }
    '/__robots__/debug-path.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+robots@4.0.2_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3_5ypj5ppfq3c6kjdx7sb4j642ty/node_modules/@nuxtjs/robots/dist/runtime/nitro/server/__robots__/debug-path').default>>>>
    }
    '/sitemap_index.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap_index.xml').default>>>>
    }
    '/pages-sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/middleware/[sitemap]-sitemap.xml').default>>>>
    }
    '/posts-sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/middleware/[sitemap]-sitemap.xml').default>>>>
    }
    '/help-sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/middleware/[sitemap]-sitemap.xml').default>>>>
    }
    '/__sitemap__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/__sitemap__/debug').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap.xml').default>>>>
    }
    '/__og-image__/font/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@3.0.0-rc.64_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5_qkcgep76462eg4tttvotfrvcmu/node_modules/nuxt-og-image/dist/runtime/nitro/routes/font').default>>>>
    }
    '/__og-image__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@3.0.0-rc.64_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5_qkcgep76462eg4tttvotfrvcmu/node_modules/nuxt-og-image/dist/runtime/nitro/routes/debug.json').default>>>>
    }
    '/__og-image__/image/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@3.0.0-rc.64_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5_qkcgep76462eg4tttvotfrvcmu/node_modules/nuxt-og-image/dist/runtime/nitro/routes/image').default>>>>
    }
    '/__schema-org__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-schema-org@3.3.9_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31._kzwlsvfawaad24ep7llb3hnehq/node_modules/nuxt-schema-org/dist/runtime/nitro/routes/__schema-org__/debug').default>>>>
    }
    '/__link-checker__/inspect': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-link-checker@3.1.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_qz632okxzowueqftu7wqgjykmi/node_modules/nuxt-link-checker/dist/runtime/nitro/routes/__link-checker__/inspect').default>>>>
    }
    '/__link-checker__/links': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-link-checker@3.1.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_qz632okxzowueqftu7wqgjykmi/node_modules/nuxt-link-checker/dist/runtime/nitro/routes/__link-checker__/links').default>>>>
    }
    '/__link-checker__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-link-checker@3.1.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_qz632okxzowueqftu7wqgjykmi/node_modules/nuxt-link-checker/dist/runtime/nitro/routes/__link-checker__/debug').default>>>>
    }
  }
}
export {}