// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type IsAny<T> = 0 extends 1 & T ? true : false
type InjectionType<A extends Plugin> = IsAny<A> extends true ? unknown : A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.0.0_eslint@8.56.0_ioredis@5.4.1_magicast@0.3_2vjq6nn6zr6vkankfqsox74fj4/node_modules/nuxt/dist/app/plugins/navigation-repaint.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.0.0_eslint@8.56.0_ioredis@5.4.1_magicast@0.3_2vjq6nn6zr6vkankfqsox74fj4/node_modules/nuxt/dist/app/plugins/check-outdated-build.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.0.0_eslint@8.56.0_ioredis@5.4.1_magicast@0.3_2vjq6nn6zr6vkankfqsox74fj4/node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.0.0_eslint@8.56.0_ioredis@5.4.1_magicast@0.3_2vjq6nn6zr6vkankfqsox74fj4/node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.0.0_eslint@8.56.0_ioredis@5.4.1_magicast@0.3_2vjq6nn6zr6vkankfqsox74fj4/node_modules/nuxt/dist/app/plugins/chunk-reload.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.0.0_eslint@8.56.0_ioredis@5.4.1_magicast@0.3_2vjq6nn6zr6vkankfqsox74fj4/node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.0.0_eslint@8.56.0_ioredis@5.4.1_magicast@0.3_2vjq6nn6zr6vkankfqsox74fj4/node_modules/nuxt/dist/pages/runtime/plugins/router").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.0.0_eslint@8.56.0_ioredis@5.4.1_magicast@0.3_2vjq6nn6zr6vkankfqsox74fj4/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.0.0_eslint@8.56.0_ioredis@5.4.1_magicast@0.3_2vjq6nn6zr6vkankfqsox74fj4/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.3.9_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.3.9_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@vueuse+motion@2.2.3_magicast@0.3.4_rollup@4.19.1_vue@3.4.34_typescript@5.5.4_/node_modules/@vueuse/motion/dist/runtime/templates/motion").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@formkit+auto-animate@0.8.2/node_modules/@formkit/auto-animate/nuxt/runtime/plugin").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+seo@2.0.0-rc.16_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0__45hin4pcwog5olgsi7vg53azo4/node_modules/@nuxtjs/seo/dist/runtime/nuxt/plugin/titles").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+seo@2.0.0-rc.16_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0__45hin4pcwog5olgsi7vg53azo4/node_modules/@nuxtjs/seo/dist/runtime/nuxt/plugin/defaults").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-link-checker@3.1.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_qz632okxzowueqftu7wqgjykmi/node_modules/nuxt-link-checker/dist/runtime/nuxt/plugin/ui.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-experiments@4.0.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@_wfjahefcl25lpsyv7zvg7pbhem/node_modules/nuxt-seo-experiments/dist/runtime/nuxt/plugins/1.absoluteImageUrls.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-experiments@4.0.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@_wfjahefcl25lpsyv7zvg7pbhem/node_modules/nuxt-seo-experiments/dist/runtime/nuxt/plugins/0.routeRules.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-experiments@4.0.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@_wfjahefcl25lpsyv7zvg7pbhem/node_modules/nuxt-seo-experiments/dist/runtime/nuxt/plugins/siteConfig").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-experiments@4.0.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@_wfjahefcl25lpsyv7zvg7pbhem/node_modules/nuxt-seo-experiments/dist/runtime/nuxt/plugins/inferSeoMetaPlugin").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-schema-org@3.3.9_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31._kzwlsvfawaad24ep7llb3hnehq/node_modules/nuxt-schema-org/dist/runtime/nuxt/plugin/defaults").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-schema-org@3.3.9_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31._kzwlsvfawaad24ep7llb3hnehq/node_modules/nuxt-schema-org/dist/runtime/nuxt/plugin/init").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-og-image@3.0.0-rc.64_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5_qkcgep76462eg4tttvotfrvcmu/node_modules/nuxt-og-image/dist/runtime/nuxt/plugins/og-image-canonical-urls.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-og-image@3.0.0-rc.64_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5_qkcgep76462eg4tttvotfrvcmu/node_modules/nuxt-og-image/dist/runtime/nuxt/plugins/route-rule-og-image.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+robots@4.0.2_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3_5ypj5ppfq3c6kjdx7sb4j642ty/node_modules/@nuxtjs/robots/dist/runtime/nuxt/plugins/robot-meta.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/nuxt/plugins/0.siteConfig").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.18.2_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3__vue@3.4.34_typescript@5.5.4_/node_modules/@nuxt/ui/dist/runtime/plugins/slideovers").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.18.2_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3__vue@3.4.34_typescript@5.5.4_/node_modules/@nuxt/ui/dist/runtime/plugins/modals").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.18.2_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3__vue@3.4.34_typescript@5.5.4_/node_modules/@nuxt/ui/dist/runtime/plugins/colors").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.4.2_magicast@0.3.4_rollup@4.19.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.4.2_magicast@0.3.4_rollup@4.19.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.3.1_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3__vue@3.4.34_typescript@5.5.4_/node_modules/@nuxt/icon/dist/runtime/plugin").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.0.0_eslint@8.56.0_ioredis@5.4.1_magicast@0.3_2vjq6nn6zr6vkankfqsox74fj4/node_modules/nuxt/dist/app/plugins/dev-server-logs").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.0.0_eslint@8.56.0_ioredis@5.4.1_magicast@0.3_2vjq6nn6zr6vkankfqsox74fj4/node_modules/nuxt/dist/app/plugins/check-if-layout-used").default> &
  InjectionType<typeof import("../../modules/directus/runtime/plugins/directus").default> &
  InjectionType<typeof import("../../modules/directus/runtime/plugins/auth").default> &
  InjectionType<typeof import("../../plugins/dompurify-html").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt-site-config:init' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt-seo:fallback-titles' | 'nuxt-seo:defaults' | 'nuxt-schema-org:defaults' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed' | 'nuxt-schema-org:init'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
