// Generated by @nuxtjs/sitemap

declare module 'nitropack' {
  interface NitroRouteRules {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/runtime/types').SitemapItemDefaults
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/runtime/types').SitemapItemDefaults
  }
  interface NitroRuntimeHooks {
    'sitemap:index-resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/runtime/types').SitemapIndexRenderCtx) => void | Promise<void>
    'sitemap:resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/runtime/types').SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/runtime/types').SitemapOutputHookCtx) => void | Promise<void>
  }
}
declare module 'vue-router' {
    interface RouteMeta {
        sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@5.3.5_h3@1.12.0_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_te_2vc454inleotrwafoqxvosrtte/node_modules/@nuxtjs/sitemap/runtime/types').SitemapItemDefaults
    }
}

export {}
