// Generated by nuxt-robots

declare module 'nitropack' {
  interface NitroApp {
    _robots: {
      ctx: import('../../node_modules/.pnpm/@nuxtjs+robots@4.0.2_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3_5ypj5ppfq3c6kjdx7sb4j642ty/node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsConfigContext
      nuxtContentUrls: Set<string>
    },
    _robotsRuleMactcher: (url: string) => string
  }
  interface NitroRouteRules {
    /**
     * @deprecated Use `robots: <boolean>` instead.
     */
    index?: boolean
    robots?: boolean | string | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRouteConfig {
    /**
     * @deprecated Use `robots: <boolean>` instead.
     */
    index?: boolean
    robots?: boolean | string | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRuntimeHooks {
    'robots:config': (ctx: import('../../node_modules/.pnpm/@nuxtjs+robots@4.0.2_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3_5ypj5ppfq3c6kjdx7sb4j642ty/node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsConfigContext) => void | Promise<void>
    'robots:robots-txt': (ctx: import('../../node_modules/.pnpm/@nuxtjs+robots@4.0.2_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.31.3_5ypj5ppfq3c6kjdx7sb4j642ty/node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsTxtContext) => void | Promise<void>
  }
}
declare module 'h3' {
  interface H3EventContext {
    robots: {
      rule: string
      indexable: boolean
    }
  }
}

export {}
