// Generated by nuxt-site-config

declare module 'nitropack' {
  interface NitroRouteRules {
    site?: import('../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigInput
  }
  interface NitroRouteConfig {
    site?: import('../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/types').SiteConfig
  }
  interface NitroRuntimeHooks {
    'site-config:init': (ctx: import('../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/types').HookSiteConfigInitContext) => void | Promise<void>
  }
}

declare module 'h3' {
  interface H3EventContext {
    siteConfig: import('../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigStack
    siteConfigNitroOrigin: string
  }
}

declare module 'nuxt/schema' {
  interface AppConfigInput {
    /** Theme configuration */
    site?: import('../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigInput
  }
  interface Nuxt {
    _siteConfig?: import('../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigStack
  }
}

declare module '@nuxt/schema' {
  interface AppConfigInput {
    /** Theme configuration */
    site?: import('../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigInput
  }
  interface Nuxt {
    _siteConfig?: import('../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigStack
  }
}
declare module 'nuxt/app' {
  interface NuxtApp {
     $nuxtSiteConfig: import('../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigResolved
  }
}
declare module '#app' {
  interface NuxtApp {
    $nuxtSiteConfig: import('../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigResolved
  }
}
declare global {
  interface Window {
    __NUXT_SITE_CONFIG__: import('../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.4_rollup@4.19.1_vite@5.3.5_@types+node@22.0.0_terser@5.3_o5rtvnezlkgfuxtbj4smkjdzqe/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigResolved
  }
}

export {}
