services:
  directus:
    image: directus/directus:11.1.0
    container_name: directus
    restart: always  
    env_file:
      - .env
    ports:
      - "8055:8055"
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      # Database settings
      DB_CLIENT: ${SUPABASE_DB_CLIENT}
      DB_HOST: ${SUPABASE_DB_HOST}
      DB_PORT: ${SUPABASE_DB_PORT}
      DB_DATABASE: ${SUPABASE_DB_DATABASE}
      DB_USER: ${SUPABASE_DB_USER}
      DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
      # Admin settings
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      # URL
      # Make sure to set this in production
      # See https://docs.directus.io/self-hosted/config-options#general
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}  
      # CORS settings for production
      # CORS_ENABLED: 'true'
      # CORS_ORIGIN: 'https://2kingsdesign.nl,https://www.2kingsdesign.nl'
      # CORS_METHODS: 'GET,POST,PATCH,DELETE'
      # CORS_ALLOWED_HEADERS: 'Content-Type,Authorization'
      # CORS_EXPOSED_HEADERS: 'Content-Range'
      # CORS_CREDENTIALS: 'true'
      # CORS_MAX_AGE: '18000'

      # These is helpful for local developement but should probably be removed in production
      # CORS_ENABLED: 'true'
      # REFRESH_TOKEN_COOKIE_DOMAIN: 'localhost'
      # EXTENSIONS_AUTO_RELOAD: 'true'
      # WEBSOCKETS_ENABLED: 'true'

      # The default config prevents importing files from 0.0.0.0. 
      # See https://docs.directus.io/self-hosted/config-options.html#security
      # This can be removed in production but in local development it is recommended to keep it so you can import logos from Organization > website.
      IMPORT_IP_DENY_LIST: ''
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./templates:/directus/templates
      - ./run-scripts:/directus/run-scripts

  # agencyos:
  #   image: timmeulendijk/agencyos:latest
  #   container_name: agencyos
  #   restart: always
  #   env_file:
  #     - .env.agencyos
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - directus